"use client";

import { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface Props {
  profileId: string;
  profileName: string;
}

export default function KarmaDNA({ profileId, profileName }: Props) {
  const [report, setReport] = useState("");
  const [meta, setMeta] = useState<{ model: string; d12: boolean; d60: boolean } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [generated, setGenerated] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    async function checkSaved() {
      if (!profileId) return;
      setLoading(true);
      try {
        const res = await fetch(`/api/karma-dna?profileId=${profileId}`);
        const data = await res.json();
        if (data.found && data.reportData) {
          setReport(data.reportData.report);
          setMeta({ 
            model: data.reportData.model, 
            d12: data.reportData.d12Available, 
            d60: data.reportData.d60Available 
          });
          setGenerated(true);
        } else {
          setGenerated(false);
          setReport("");
        }
      } catch (err) {
        console.error("Failed to check saved report", err);
      } finally {
        setLoading(false);
      }
    }
    checkSaved();
  }, [profileId]);

  const generate = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/karma-dna", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ profileId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to generate");
      setReport(data.report);
      setMeta({ model: data.model, d12: data.d12Available, d60: data.d60Available });
      setGenerated(true);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const content = printRef.current;
    if (!content) return;

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <title>Karma DNA Report — ${profileName}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', sans-serif;
      color: #1e293b;
      background: #fff;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      text-align: center;
      padding: 30px 0;
      border-bottom: 2px solid #e2e8f0;
      margin-bottom: 30px;
    }
    .header h1 { font-size: 28px; font-weight: 700; color: #4f46e5; }
    .header p  { color: #64748b; font-size: 14px; margin-top: 4px; }
    .badge {
      display: inline-block;
      background: #f1f5f9; border: 1px solid #e2e8f0;
      padding: 4px 12px; border-radius: 100px;
      font-size: 11px; font-weight: 600; color: #475569;
      margin: 8px 4px 0;
    }
    h2 { font-size: 18px; font-weight: 700; color: #1e293b; margin: 24px 0 10px; }
    h3 { font-size: 14px; font-weight: 700; color: #4f46e5; margin: 16px 0 6px; }
    p  { font-size: 14px; line-height: 1.8; color: #334155; margin-bottom: 10px; }
    li { font-size: 14px; line-height: 1.8; color: #334155; margin-left: 20px; margin-bottom: 4px; }
    strong { color: #1e293b; }
    em     { color: #6366f1; font-style: italic; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
    blockquote { border-left: 3px solid #6366f1; padding-left: 16px; color: #475569; font-style: italic; }
    .footer {
      text-align: center;
      padding: 24px 0;
      border-top: 2px solid #e2e8f0;
      margin-top: 40px;
      color: #94a3b8;
      font-size: 11px;
    }
    @media print {
      body { padding: 20px; }
      .footer { position: fixed; bottom: 0; left: 0; right: 0; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🧬 Karma DNA Report</h1>
    <p>A Sacred Soul Blueprint — Quantum Karma</p>
    <div>
      <span class="badge">For: ${profileName}</span>
      <span class="badge">Generated: ${new Date().toLocaleDateString("en-IN", { day:"numeric", month:"long", year:"numeric" })}</span>
      <span class="badge">Model: Quantum Oracle</span>
    </div>
  </div>
  ${content.innerHTML}
  <div class="footer">
    <p>This report is generated by Quantum Karma AI using Indian Vedic Astrology.</p>
    <p>Confidential — For ${profileName} only · quantumkarma.tech</p>
  </div>
</body>
</html>`);
    printWindow.document.close();
    setTimeout(() => { printWindow.focus(); printWindow.print(); }, 500);
  };

  return (
    <div data-lenis-prevent className="h-full flex flex-col overflow-y-auto custom-scrollbar">
      {/* Header */}
      <div className="flex-shrink-0 px-4 md:px-10 py-4 md:py-5 border-b border-slate-100 bg-gradient-to-r from-purple-50 via-indigo-50/60 to-slate-50">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xl flex-shrink-0">🧬</span>
              <h2 className="text-base md:text-xl font-black text-slate-900 tracking-tight leading-tight">Karma DNA Report</h2>
            </div>
            <p className="text-xs md:text-sm text-slate-500 leading-relaxed">Past-life karma, soul contracts & dharmic mission · {profileName}</p>
            {meta && (
              <div className="flex gap-1.5 mt-2 flex-wrap">
                <span className="text-[11px] bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full font-semibold">
                  Quantum Oracle
                </span>
                <span className={`text-[11px] px-2 py-0.5 rounded-full font-semibold ${meta.d12 ? "bg-green-100 text-green-700" : "bg-orange-100 text-orange-700"}`}>
                  D12: {meta.d12 ? "✓" : "Est."}
                </span>
                <span className={`text-[11px] px-2 py-0.5 rounded-full font-semibold ${meta.d60 ? "bg-green-100 text-green-700" : "bg-orange-100 text-orange-700"}`}>
                  D60: {meta.d60 ? "✓" : "Est."}
                </span>
              </div>
            )}
          </div>
          {generated && (
            <button
              onClick={handlePrint}
              className="flex-shrink-0 p-2 md:px-4 md:py-2.5 bg-white border border-slate-200 text-slate-700 text-sm font-semibold rounded-xl hover:bg-slate-50 transition-all flex items-center gap-2"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/>
                <rect x="6" y="14" width="12" height="8"/>
              </svg>
              <span className="hidden md:inline">Print / PDF</span>
            </button>
          )}
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="mx-6 md:mx-10 mt-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">
          {error}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="flex-1 flex flex-col items-center justify-center gap-6">
          <div className="relative">
            <div className="w-16 h-16 rounded-full border-4 border-purple-100 border-t-purple-500 animate-spin" />
            <div className="absolute inset-0 flex items-center justify-center text-2xl">🧬</div>
          </div>
          <div className="text-center">
            <p className="font-semibold text-slate-700 mb-1">Consulting the Akashic Records</p>
            <p className="text-sm text-slate-400">Analyzing D1, D9, D12, D60 + Nadi + Jaimini...</p>
          </div>
          <div className="flex flex-wrap justify-center gap-x-4 gap-y-2 text-xs text-slate-400 px-4">
            {["Fetching D12","Fetching D60","Calling Oracle","Generating"].map((step, i) => (
              <div key={i} className="flex items-center gap-1.5">
                <div className="w-1.5 h-1.5 bg-purple-400 rounded-full animate-pulse" style={{ animationDelay: `${i * 0.3}s` }} />
                {step}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Idle — Pre-generation */}
      {!generated && !loading && (
        <div className="flex-1 flex flex-col items-center justify-center gap-5 p-5 md:p-8 text-center">
          <div className="text-6xl">🧬</div>
          <div>
            <h3 className="text-lg font-bold text-slate-800 mb-2">Your Soul's Sacred Blueprint</h3>
            <p className="text-sm text-slate-500 max-w-sm">
              A deep, personal exploration of your past-life karma patterns, Saturn/Rahu/Ketu analysis, soul contracts, and dharmic mission — from D1, D9, D12 & D60.
            </p>
          </div>

          {/* What's included */}
          <div className="grid grid-cols-2 gap-3 text-left w-full max-w-md">
            {[
              { icon: "🔮", title: "Atmakaraka Soul Reading", desc: "Past-life soul mission" },
              { icon: "🌑", title: "Saturn · Rahu · Ketu", desc: "The karma trio analysis" },
              { icon: "📜", title: "D60 Shashtiamsha", desc: "Soul-level karma map" },
              { icon: "👪", title: "D12 Ancestral Karma", desc: "Parental soul contracts" },
              { icon: "💑", title: "Jaimini Karakas", desc: "AK, DK, AL, UL analysis" },
              { icon: "🕉️", title: "48-Day Mantra Protocol", desc: "Karma clearing practice" },
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-lg">{item.icon}</span>
                <div>
                  <p className="text-xs font-bold text-slate-700">{item.title}</p>
                  <p className="text-xs text-slate-400">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 max-w-sm text-left">
            <p className="text-xs font-bold text-amber-800 mb-1">⚡ Premium Report</p>
            <p className="text-xs text-amber-700">This deep analysis costs 20 credits. It uses D12 & D60 divisional charts for maximum depth and accuracy.</p>
          </div>

          {!confirmed ? (
            <button
              onClick={() => setConfirmed(true)}
              className="px-8 py-3 bg-purple-600 text-white font-semibold rounded-xl hover:bg-purple-700 shadow-lg shadow-purple-200 transition-all"
            >
              Generate Karma DNA · 20 Credits
            </button>
          ) : (
            <div className="flex flex-col items-center gap-3">
              <p className="text-sm font-semibold text-slate-700">Confirm 20 credit deduction?</p>
              <div className="flex gap-3">
                <button onClick={() => setConfirmed(false)} className="px-5 py-2.5 bg-slate-100 text-slate-600 font-semibold rounded-xl hover:bg-slate-200 text-sm transition-all">
                  Cancel
                </button>
                <button onClick={generate} className="px-5 py-2.5 bg-purple-600 text-white font-semibold rounded-xl hover:bg-purple-700 shadow-lg shadow-purple-200 text-sm transition-all">
                  Yes, Generate Report
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Report Output — FULL WIDTH PREMIUM LAYOUT */}
      {generated && report && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex-1 overflow-y-auto custom-scrollbar"
        >
          {/* Print/download bar */}
          <div className="sticky top-0 bg-white/95 backdrop-blur-sm border-b border-slate-100 px-6 md:px-10 py-3 flex items-center justify-between z-10">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-emerald-500 rounded-full" />
              <span className="text-xs font-semibold text-slate-600">Report Generated · Quantum Oracle</span>
            </div>
            <button onClick={handlePrint} className="text-xs font-semibold text-indigo-600 hover:text-indigo-700 flex items-center gap-1.5">
              <span>Save as PDF</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            </button>
          </div>

          {/* Report content — FULL WIDTH, no max-w constraint */}
          <div className="px-4 md:px-8 lg:px-12 py-5 md:py-8">
            <div ref={printRef}>
              <div className="karma-dna-report">
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    h1: ({ children }) => (
                      <h1 className="text-2xl font-black text-slate-900 tracking-tight mb-4 mt-2">
                        {children}
                      </h1>
                    ),
                    h2: ({ children }) => (
                      <div className="mt-10 mb-5">
                        <div className="flex items-center gap-3 mb-3">
                          <div className="w-1.5 h-8 rounded-full bg-gradient-to-b from-purple-500 to-indigo-600" />
                          <h2 className="text-[19px] font-black text-slate-900 tracking-tight uppercase">
                            {children}
                          </h2>
                        </div>
                        <div className="h-px bg-gradient-to-r from-purple-200 via-indigo-100 to-transparent" />
                      </div>
                    ),
                    h3: ({ children }) => (
                      <h3 className="text-[15px] font-extrabold text-indigo-700 mt-7 mb-2.5 flex items-center gap-2">
                        <span className="w-1 h-1 rounded-full bg-indigo-400 flex-shrink-0" />
                        {children}
                      </h3>
                    ),
                    h4: ({ children }) => (
                      <h4 className="text-sm font-bold text-slate-700 mt-5 mb-2">{children}</h4>
                    ),
                    p: ({ children }) => (
                      <p className="text-[15px] text-slate-700 leading-[1.85] mb-4 font-normal">{children}</p>
                    ),
                    strong: ({ children }) => (
                      <strong className="font-extrabold text-slate-900">{children}</strong>
                    ),
                    em: ({ children }) => (
                      <em className="text-indigo-600 font-medium not-italic">{children}</em>
                    ),
                    hr: () => (
                      <div className="my-8 flex items-center gap-3">
                        <div className="flex-1 h-px bg-gradient-to-r from-transparent via-slate-200 to-transparent" />
                        <span className="text-slate-300 text-xs">✦</span>
                        <div className="flex-1 h-px bg-gradient-to-r from-transparent via-slate-200 to-transparent" />
                      </div>
                    ),
                    blockquote: ({ children }) => (
                      <div className="my-5 relative">
                        <div className="absolute left-0 top-0 bottom-0 w-1 rounded-full bg-gradient-to-b from-indigo-500 to-purple-500" />
                        <div className="pl-5 pr-4 py-3 bg-gradient-to-r from-indigo-50/80 to-transparent rounded-r-xl">
                          <div className="text-[14px] text-indigo-800 leading-relaxed font-medium italic">
                            {children}
                          </div>
                        </div>
                      </div>
                    ),
                    ul: ({ children }) => (
                      <ul className="space-y-2.5 my-4 pl-0 list-none">{children}</ul>
                    ),
                    ol: ({ children }) => (
                      <ol className="space-y-2.5 my-4 pl-0 list-none counter-reset-item">{children}</ol>
                    ),
                    li: ({ children }) => (
                      <li className="flex gap-3 text-[15px] text-slate-700 leading-relaxed">
                        <span className="flex-shrink-0 w-5 h-5 mt-0.5 rounded-md bg-purple-100 flex items-center justify-center">
                          <span className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                        </span>
                        <span className="flex-1">{children}</span>
                      </li>
                    ),
                    table: ({ children }) => (
                      <div className="my-6 overflow-x-auto rounded-xl border border-slate-200 shadow-sm">
                        <table className="w-full text-sm border-collapse">{children}</table>
                      </div>
                    ),
                    thead: ({ children }) => (
                      <thead className="bg-gradient-to-r from-slate-800 to-slate-700">{children}</thead>
                    ),
                    th: ({ children }) => (
                      <th className="text-left px-5 py-3 text-xs font-bold text-white uppercase tracking-wider">{children}</th>
                    ),
                    td: ({ children }) => (
                      <td className="px-5 py-3 text-slate-700 font-medium border-t border-slate-100">{children}</td>
                    ),
                    tr: ({ children }) => (
                      <tr className="even:bg-slate-50/70 hover:bg-indigo-50/40 transition-colors">{children}</tr>
                    ),
                    a: ({ href, children }) => (
                      <a href={href} className="text-indigo-600 font-semibold underline decoration-indigo-300 underline-offset-2 hover:text-indigo-800 transition-colors" target="_blank" rel="noopener noreferrer">{children}</a>
                    ),
                    code: ({ children }) => (
                      <span className="bg-indigo-50 text-indigo-700 text-[13px] font-semibold px-2 py-0.5 rounded-md border border-indigo-100">{children}</span>
                    ),
                  }}
                >
                  {report}
                </ReactMarkdown>
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}
